export function createNewCard() {
    return {
        cardId: 1,
        agentDetails: {
            fullName: "",
            rule: "",
            mobile: "",
            personalEmail: "",
            aboutConnect: "",
            aboutTitle: "",
            personalMassegeTitle: "",
            personalMassegeConnect: "",
        },
        socialMedias: [
            { name: "Whatsapp", url: "" },
            { name: "Facebook", url: "" },
            { name: "Messenger", url: "" },
            { name: "Youtube", url: "" },
            { name: "Instagram", url: "" },
            { name: "Twitter", url: "" },
            { name: "Linkedin", url: "" },
            { name: "Slack", url: "" },
            { name: "Dribbble", url: "" },
            { name: "Waze", url: "" },
        ],
        vCardStyle: {
            coverImg: "",
            bodyColor: "#2B5FFF",
            bodyColorDesktop: "#fff",
            logoImg: "#15328A 0% 0% no-repeat padding-box",
            logoShape: "",
            profileImg: "#15328A 0% 0% no-repeat padding-box",
            profileImgShape: "",
            fullNametitleColor: "#fff",
            fullNametitleColorDesktop: "#0D214B",
            ruletitleColor: "#fff",
            ruletitleColorDesktop: "#0D214B",
            mobiletitleColor: "",
            mobiletitle: "Call Me",
            mobileIconColor: "",
            socialMediaIconColor: "#fff",
            socialMediaTitleIconColor: "#fff",
            socialMediaIconColorDesktop: "#0D214B",
            socialMediaTitleIconColorDesktop: "#0D214B",
            socialMediaIconShape: "50%",
            fullNameShow: false,
            ruleShow: false,
            mobileShow: false,
            profileShow: false,
            mobileIconShow: false,
            aboutShow: false,
            personalMassegeShow: false
        }
    }
}